services:
  samba:
    container_name: samba
    image: dockurr/samba
    ports:
      - "445:445/tcp"

    environment:
      NAME: "Data"
      USER: "samba"
      PASS: "super_secret_password"

    volumes:
      - "./samba:/storage"

    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"

    environment:
      TZ: 'America/Los_Angeles'
      FTLCONF_webserver_api_password: 'super_secret_password'
      FTLCONF_dns_listeningMode: 'all'

    volumes:
      - './etc-pihole:/etc/pihole'

    restart: unless-stopped
